#!/bin/sh
# Copyright (C) 2026 Qore Technologies, s.r.o.
# SPDX-License-Identifier: MIT
set -eu
export LC_ALL=C.UTF-8
unset QORE_MODULE_DIR QORE_MODULE_DIR_ONLY QORE_INCLUDE_DIR LD_LIBRARY_PATH LD_PRELOAD
mkdir -p "${QORE_RPM_TEST_TMP:?set QORE_RPM_TEST_TMP}"
cp test/*.qtest rpm/features.qr "$QORE_RPM_TEST_TMP/"
cd "$QORE_RPM_TEST_TMP"
/usr/bin/qore -b --enable-debug features.qr
for suite in ./*.qtest; do
    timeout 600 /usr/bin/qore -b --enable-debug "$suite" -v
done
