#!/bin/sh
# Copyright (C) 2026 David Nichols
# SPDX-License-Identifier: MIT
set -eu
unset QORE_MODULE_DIR QORE_MODULE_DIR_ONLY QORE_INCLUDE_DIR LD_LIBRARY_PATH LD_PRELOAD
export QORE_MODULE_DIR=$(/usr/bin/qore --module-path)
export QORE_MODULE_DIR_ONLY=1
feature_test=$(pwd)/debian/tests/features
cp test/*.qtest "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
/usr/bin/qore "$feature_test"
for test in *.qtest; do
    timeout 300 /usr/bin/qore "$test" -v
done
